[package]
name = "tvix-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
console_error_panic_hook = "0.1"
tvix-eval = { path = "../eval", default-features = false, features = [] }
bytes = "1.0"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]