#!/usr/bin/env bash

set -e

EMBED_NIX_PATH="${1}"
if [ -z "$EMBED_NIX_PATH" ]; then
    echo "No EMBED_NIX_PATH provided"
    exit 1
fi

echo "Embedding files from EMBED_NIX_PATH: $EMBED_NIX_PATH"

# Parse colon-separated NIX_PATH entries
IFS=':' read -ra PATH_ENTRIES <<< "$EMBED_NIX_PATH"

function get_nix_path_entry_name() {
    local entry="$1"
    if [[ "$entry" == *"="* ]]; then
        echo "${entry%%=*}"  # Return name part before '='
    else
        echo "$(basename "$entry")"  # Return basename of path
    fi
}

function get_nix_path_entry_path() {
    local entry="$1"
    if [[ "$entry" == *"="* ]]; then
        echo "${entry#*=}"  # Return path part after '='
    else
        echo "$entry"  # Return the entry itself as path
    fi
}

embedded_path_push_lines=()
embed_file_list_lines=()
embed_file_match_lines=()
for entry in "${PATH_ENTRIES[@]}"; do
    name=$(get_nix_path_entry_name "$entry")
    embedded_path_push_lines+=("embedded_paths.push(\"$name\".to_string());")
    path=$(get_nix_path_entry_path "$entry")
    nix_file_paths=($(find -H "$path" -name "*.nix"))
    for nix_file_path in "${nix_file_paths[@]}"; do
        embedded_path="embedded/${name}${nix_file_path#"$path"}"
        echo "Embedding ${nix_file_path} -> ${embedded_path}" 1>&2
        embedded_file_list_lines+=("\"$embedded_path\",")
        embedded_file_match_lines+=("\"$embedded_path\" => {")
        embedded_file_match_lines+=("    fs.insert(embedded_path.to_string(), include_str!(\"$nix_file_path\").to_string());")
        embedded_file_match_lines+=("},")
    done
done

function generate_embedded_lib() {
    cat << EOF
// DO NOT EDIT MANUALLY
// Auto-generated by generate-embed-function.sh

use wasm_bindgen::prelude::*;
use std::collections::HashMap;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

pub fn embed_directory(fs: &mut HashMap<String, String>, embedded_paths: &mut Vec<String>) {
EOF

    for l in "${embedded_path_push_lines[@]}"; do
        echo "    $l"
    done

    cat << EOF
    let all_embedded_paths = [
EOF

    for l in "${embedded_file_list_lines[@]}"; do
        echo "        $l"
    done

    cat << EOF
    ];

    for embedded_path in all_embedded_paths {
        log(&format!("VFS: Embedding file: {}", embedded_path));
        match embedded_path {
EOF

    for l in "${embedded_file_match_lines[@]}"; do
        echo "            $l"
    done

    cat << EOF
            _ => {
                log(&format!("VFS: Warning - file not embedded: {}", embedded_path));
            }
        }
    }
}
EOF
}

mkdir -p src/generated
generate_embedded_lib > src/generated/mod.rs
echo "Embedded ${#embedded_file_list_lines[@]} files into src/generated/mod.rs"
